### ISSUE TITLE
Hours are not minutes

### ISSUE THREAD

**Issue by imcitius** [rodgetech/cron-ai#12]
This is just wrong. :)

![IMAGE 2023-02-23 15:30:10](https://user-images.githubusercontent.com/10992191/220920694-f5c81f3a-dd8f-4e9e-a1b9-5aebbe6f2acc.jpg)

**Comment by rodgetech** [comment]
Indeed, will look into this.

**Comment by rodgetech** [comment]
Seems to be fixed in #14
