### ISSUE TITLE
Only works for very easy cron expressions

### ISSUE THREAD

**Issue by virtualmarc** [rodgetech/cron-ai#5]
As soon as cron expressions get a bit more complicated it creates invalid output which is not only partially wrong but also invalid cron syntax (e.g. containing 6 or 7 parameters instead of 5).

Examples:

Prompt: `every uneven minute, every even hour on all mondays on every month with 31 days`
Output: `0 */2 * * 1 1,3,5,7,8,10,12 31`

Prompt: `every 15 minutes, every even hour on all mondays on every month with 31 days`
Output: `0 0/2 * * 1 1,3,5,7,8,10,12 31`

Prompt: `every 15 minutes on every fourth hour every 7 days on every month`
Output: `0 0/4 * * 0/7 *`

Prompt: `every half an hour on mid day on every monday, wednesday and saturday`
Output: `0 30 12 * * 1,3,6`
(This example way corrent until I added the weekdays)

even some simple tasks fail:

Prompt: `every 15 minutes`
Output: `*/0 */15 * * *`

**Comment by rodgetech** [comment]
Indeed. In most scenarios, I was only testing prompts for trivial cron expressions as these are what I tend to use on a daily basis. I recently released #6 which helps a little with the accuracy of results by confirming the generated cron express to a regex.
