### ISSUE TITLE
Add it GSOC 

### ISSUE THREAD

**Issue by cleverhare** [rodgetech/cron-ai#7]
it would boost the popularity bu 50x I can guarantee

**Comment by rodgetech** [comment]
Interesting idea but I'm not an organization so I'm not sure how I would submit it.

**Comment by cleverhare** [comment]
I participate in this but I am not sure how this is going to be done, Maybe youshould register yourself as organization over there and share this repo link there. go to GSoC website to know more

**Comment by rodgetech** [comment]
Ok thanks, well check it out.
